<?php
$form = $this->form;
/* @var $form \Admin\Form\ServiceForm */
$form->prepare();
$form->setAttribute('method', 'post');

$title = $form->get('title');
$description = $form->get('description');
$url = $form->get('url');
$image = $form->get('image');
$panorama = $form->get('panorama_file');
$date_published = $form->get('date_published');
$category_id = $form->get('service_category_id');

$submitElement = $form->get('submit');
?>
<h1>Въвеждане на услуга</h1>
<div class="row">
    <div class="col-md-5 col-lg-5">
        <?php echo $this->form()->openTag($form) ?>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($category_id) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $category_id->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($category_id);
                echo $this->formElement($category_id->setAttributes(array('class' => 'form-control text-input', 'id' => 'category_id')));
                ?>
            </div>
            <?php if ($this->formElementErrors($category_id)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($category_id); ?></div>
            <?php } ?>
        </div>

        <div class="form-group form-elements <?php echo ($this->formElementErrors($title) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $title->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($title);
                echo $this->formElement($title->setAttributes(array('class' => 'form-control text-input', 'id' => 'title')));
                ?>
            </div>
            <?php if ($this->formElementErrors($title)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($title); ?></div>
            <?php } ?>
        </div>

        <div class="form-group form-elements <?php echo ($this->formElementErrors($description) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $description->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($description);
                echo $this->formElement($description->setAttributes(array('class' => 'form-control text-input', 'id' => 'description')));
                ?>
            </div>
            <?php if ($this->formElementErrors($description)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($description); ?></div>
            <?php } ?>
        </div>                                

        <div class="form-group form-elements <?php echo ($this->formElementErrors($image) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $image->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($image);
                echo $this->formElement($image->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($image)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($image); ?></div>
            <?php } ?>
        </div>      

        <div class="form-group form-elements <?php echo ($this->formElementErrors($panorama) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $panorama->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($panorama);
                echo $this->formElement($panorama->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($panorama)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($panorama); ?></div>
            <?php } ?>            
        </div>


        <div class="form-group form-elements <?php echo ($this->formElementErrors($date_published) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $date_published->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($date_published);
                ?>
                <?php echo $this->formElement($date_published->setAttributes(array('class' => 'form-control', 'id' => 'date_published'))); ?>
                <?php echo $this->formElementErrors($date_published); ?>
                <script>
                    calendarDateTimePicker('#date_published');
                </script>
            </div>
            <?php if ($this->formElementErrors($date_published)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($date_published); ?></div>
            <?php } ?>
        </div>                







        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <button id="serviceBack" class="btn btn-success">Назад</button>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script>
    tinymce.init({
        selector: '#description',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table contextmenu paste code'
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'
    });
</script>
<script type="text/javascript">

    $(document).ready(function () {
        setInterval(function () {
            var height = $('#description_ifr').contents().find('body').height() + 20;
            $('#description_ifr').height(Math.max(height, 300));
        }, 1);
    });

    document.getElementById("serviceBack").onclick = function (event) {
        event.preventDefault();
        location.href = '<?php echo $this->url('languageRoute/adminService'); ?>';
    };

</script>