<div class="site-showcase">
    <div class="parallax page-header"
         style="background-image:url(/img/blog-bg.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 style="text-shadow: 1px 1px 1px #000;"><?php echo $this->language()->translate('Cart'); ?></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <div class="page">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3 class=""><?php echo $this->language()->translate('My menu'); ?></h3>
                        <?php if(!is_null($this->logo)):?>
                            <?php if(isset($userId)): ?>
                            <img src="https://ogledi.bg/media/agents/<?php echo $userId; ?>/<?php echo $this->logo;?>" style="padding:1px; border:#ccc solid 1px;">
                            <?php endif; ?>
                        <?php endif;?>
                        <ul class="mymenulist">
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myProfile', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-pencil" aria-hidden="true"></i> <?php echo $this->language()->translate('Personal info'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myOffers', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-list" aria-hidden="true"></i> <?php echo $this->language()->translate('My offers'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myList', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-list-alt" aria-hidden="true"></i> <?php echo $this->language()->translate('My list'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myCart', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> <?php echo $this->language()->translate('Cart'); ?></a>
                            </li>
                            <?php if ($this->userType != 1) { ?>
                                <li>
                                    <a href="<?php echo $this->url('languageRoute/myAgents', array('lang' => $_SESSION['lang'])); ?>">
                                        <i class="fa fa-user" aria-hidden="true"></i> <?php echo $this->language()->translate('Brokers'); ?></a>
                                </li>       
                            <?php } ?>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myLogout', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-sign-out" aria-hidden="true"></i> <?php echo $this->language()->translate('Exit'); ?></a>
                            </li>
                        </ul>

                        <iframe id='a3288865' name='a3288865' src='https://ads.ogledi.bg/www/delivery/afr.php?zoneid=22&amp;cb=(new Date().getTime())' frameborder='0' scrolling='no' width='250' height='250'><a href='https://ads.ogledi.bg/www/delivery/ck.php?n=a7012fc3&amp;cb=(new Date().getTime())' target='_blank'><img src='https://ads.ogledi.bg/www/delivery/avw.php?zoneid=22&amp;cb=(new Date().getTime())&amp;n=a7012fc3' border='0' alt='' /></a></iframe>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <h3><?php echo $this->language()->translate('Information about bank transfer'); ?></h3>
                        <p>
                            <?php echo $this->language()->translate('Bank transfer success. Part1'); ?><br/>
                            <?php echo $this->language()->translate('Bank transfer success. Part2'); ?>
                            : <strong><?php echo $this->code; ?></strong>
                        </p>
                        <p>
                            <?php echo $this->language()->translate('Make paymeny using our bank account'); ?>:<br/>
                            <strong>
                                <?php echo $this->language()->translate('Our IBAN'); ?><br/>
                                <?php echo $this->language()->translate('Our BIC'); ?><br/>
                                <?php echo $this->language()->translate('Back transfer name'); ?><br/>
                                <?php echo $this->language()->translate('Recipient ogledibg'); ?><br/>
                                <?php echo $this->language()->translate('Back transfer number'); ?>&nbsp;<?php echo $this->code; ?>
                            </strong>
                        </p>
                        <p>
                            <?php echo $this->language()->translate('Back transfer 24 hours. Part1'); ?>
                        </p>
                        <p>
                            <?php echo $this->language()->translate('Back transfer 24 hours. Part2'); ?>
                        </p>
                        <p> 
                            <?php echo $this->language()->translate('Back transfer invoice. Part1'); ?>
                        </p>
                        <p>
                            <?php echo $this->language()->translate('Back transfer invoice. Part2'); ?><br/>
                            <?php echo $this->language()->translate('Back transfer invoice. Part3'); ?>
                        </p>
                        <p>
                            <?php echo $this->language()->translate('Thank you'); ?>                                                        
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>