<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>
    <body>
        <img src="https://ogledi.bg/img/ogledi.png" border="0"/>
        <br/>
        <br/>
        <p>Вие успешно заявихте заплащане на избраните от Вас услуги в сайта ogledi.bg - по банков път.<br/>Вашата заявка на поръчка е под номер: <strong>{$code}</strong></p>
        <p>Моля направете плащането по следната банкова сметка:</p>
        <p><strong>
            IBAN BG83BPBI79401083019501<br/>
             BIC BPBIBGSF<br/>
            При банка: "Юробанк И Еф Джи Груп" АД (Пощенска банка)<br/>
            Получател: ОгледиБг ООД <br/>
             Основание: Номер на заявка {$code}
            </strong></p>
        <p>В случай, че в заявката Ви има заснемане на обект, моля направете плащането в срок до 24часа, преди заявения от вас ден и час за заснемане и изпратете платежното на имейл info@ogledi.bg.</p>
        <p>В случай, че не получим плащането преди избрания ден и час за заснемане ОгледиБГ ООД си запазва правото автоматично да отмени изпращането на фотограф. В този случай, ще е нужно подновяване на заявения от Вас ден и час за заснемане, след заплащане на услугата.</p>
        <p>Ако желаете да получите фактура, изпратете на имейл: info@ogledi.bg Вашите данни за фактура в свободен текст и номера на поръчката. До 24 часа от отразяване на плащането, ще получите от нас фактурата.</p>
        <p>При затруднения от всякакво естество свържете се с нас на телефон:<br/>+359 877 555 130</p>
        <p>Благодарим Ви, че използвате ogledi.bg!</p>
        <br/>
        <hr>
        <br/>
        <p>You successfully requested payment for selected services at www.ogledi.bg by Bank transfer.<br/>Your order is under number: <strong>{$code}</strong></p>
        <p>Please make payment to the following bank account:</p>
        <p><strong>
            IBAN BG83BPBI79401083019501<br/>
             BIC BPBIBGSF<br/>
            Bank: “Юробанк България” АД<br/>
            Recipient: ОгледиБг ООД <br/>
             Warrant: Order number {$code}
            </strong></p>
        <p>In the event that your order has shooting on site, please make the payment within 24 hours, before the requested day and time for shooting and send the transfer document to: info@ogledi.bg.</p>
        <p>Failure to do so within the given deadline, we will automatically cancel the sending of photographer. In this case, you will need renewal requeste by the day and time of shooting, after the payment of the service.</p>
        <p>If you would like to receive an invoice, please email: info@ogledi.bg Your invoice details and the code numberWithin 24 hours of considering the payment, you will receive an invoice of that email.</p>
        <p>For questions contact us on:<br/>+359 877 555 130</p>
        <p>Thank you for using ogledi.bg!</p>
    </body>
</html>