<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>
    <body>
        <img src="https://ogledi.bg/img/ogledi.png" border="0"/>
        <br/>
        <br/>
        <p>Вие успешно заявихте заплащане на избраните от Вас услуги в сайта  ogledi.bg, чрез системата на  EasyPay, вашият уникален код за палщане в EasyPay е: <strong>{$code}</strong></p>
        <p>Моля запазете този код, тъй като той ще Ви бъде необходим за идентификация на поръчката при заплащането.</p>
        <p>Плащането може да извършите във всеки от офисите на <a href="http://www.easypay.bg/?p=offices" >EasyPay</a></p>
        <p>В случай, че в заявката Ви има заснемане на обект, моля направете плащането в срок до 24часа, преди заявения от вас ден и час за заснемане! Ако не сторите това в срока, ние автоматично ще отменим изпращането на фотографа. В този случай, ще е нужно подновяване на заявения от Вас ден и час за заснемане, след заплащане на услугата.</p>
        <p>Благодарим ВИ, че използвате нашия портал!</p>
        <br/>
        <hr>
        <br/>
        <p>You successfully stated a payment for the selected services in www.ogledi.bg, by the system of EasyPay. Your code for paying is <strong>{$code}</strong></p>
        <p>Please, present it in the most convenient for you EasyPay cash desk - <a href="http://www.easypay.bg/?p=offices" >See on map</a>. After the payment your transaction will automatically be entered into our system.</p>
        <p>In case, the order includes filming a site, please accomplish the payment up to 24 hours before the stated day and time of filming. If you fail to do so within the given deadline, we automatically will cancel the sending of a photographer. In this case, an order renewal is required, after paying for the service.</p>
        <p>In order to receive your invoice, please send to the email address: info@ogledi.bg data for the invoice the code number. Up to 24 hours after payment entry, you will receive an invoice on the stated email address. For questions, contact us on the phone number +359 8777 555 130.</p>
        <p>Thank you for using ogledi.bg!</p>
    </body>
</html>