<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>
    <body>
        <img src="https://ogledi.bg/img/ogledi.png" border="0"/>
        <br/>
        <br/>
        Вие успешно заявихте смяна на парола в сайта ogledi.bg, новата Ви парола е: <strong>{$password}</strong><br>
        <br/>
        <hr>
        <br/>
        You successfully requested a change of your password in ogledi.bg, your new password is: <strong>{$password}</strong><br>
    </body>
</html>