<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>
    <body>
        <img src="https://ogledi.bg/img/ogledi.png" border="0"/>
        <br/>
        <br/>
        Благодарим Ви, че се регистрирахте в поратала на ОГЛЕДИ.БГ. За да активирате Вашата регистрация, моля използвайте следния линк:<br>
        <a href="{$website}bg/verification-successful?code={$code}">{$website}bg/verification-successful?code={$code}</a>
    </body>
</html>