<?php
$regForm = $this->regForm;
$regForm->prepare();
?>

<div class="site-showcase">
    <div class="parallax page-header" style="background-image:url(/img/blog-bg.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 style="text-shadow: 1px 1px 1px #000;"><?php echo strtoupper($this->companyName); ?></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <div class="page">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">   
                        <h3 class=""><?php echo $this->language()->translate('My menu'); ?></h3>
                        <?php if(!is_null($this->logo)):?>
                        <img src="https://ogledi.bg/media/agents/<?php echo $userId; ?>/<?php echo $this->logo;?>" style="padding:1px; border:#ccc solid 1px;">
                        <?php endif;?>
                        <ul class="mymenulist">
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myProfile', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-pencil" aria-hidden="true"></i> <?php echo $this->language()->translate('Personal info'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myOffers', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-list" aria-hidden="true"></i> <?php echo $this->language()->translate('My offers'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myList', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-list-alt" aria-hidden="true"></i> <?php echo $this->language()->translate('My list'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myCart', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> <?php echo $this->language()->translate('Cart'); ?></a>
                            </li>
                            <?php if ($this->userType != 1) { ?>
                                <li>
                                    <a href="<?php echo $this->url('languageRoute/myAgents', array('lang' => $_SESSION['lang'])); ?>">
                                        <i class="fa fa-user" aria-hidden="true"></i> <?php echo $this->language()->translate('Brokers'); ?></a>
                                </li>       
                            <?php } ?>
                            <li>
                                <a href="<?php echo $this->url('languageRoute/myLogout', array('lang' => $_SESSION['lang'])); ?>">
                                    <i class="fa fa-sign-out" aria-hidden="true"></i> <?php echo $this->language()->translate('Exit'); ?></a>
                            </li>
                        </ul>

                        <iframe id='a8e48176' name='a8e48176' src='https://ads.ogledi.bg/www/delivery/afr.php?zoneid=19&amp;cb=(new Date().getTime())' frameborder='0' scrolling='no' width='250' height='250'><a href='https://ads.ogledi.bg/www/delivery/ck.php?n=aed53494&amp;cb=(new Date().getTime())' target='_blank'><img src='https://ads.ogledi.bg/www/delivery/avw.php?zoneid=19&amp;cb=(new Date().getTime())&amp;n=aed53494' border='0' alt='' /></a></iframe>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12 register-form">
                        <h3><?php echo $this->language()->translate('Personal info'); ?></h3>
                        <form action="" method="post" id="registerform" name="registrationForm" class="register-form submitthis" enctype="multipart/form-data">
                            <input type="hidden" name="registration" value="1" />
                            <div class="input-group"><span class="input-group-addon"><i class="fa fa-refresh"></i></span>
                                <?php echo $this->formElement($regForm->get('user_type_id')->setAttributes(array('class' => 'form-control selectpicker', 'id' => 'user_type_id'))); ?>
                                <?php echo $this->formElementErrors($regForm->get('user_type_id')); ?>
                            </div>
                            <script>
                                $('#user_type_id').on('change', function () {
                                    toggleCompanyUserFields();
                                });
                            </script>
                            <br>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <?php echo $this->formElement($regForm->get('names')->setAttributes(array('class' => 'form-control selectpicker', 'placeholder' => $this->language()->translate('Name')))); ?>
                                <?php echo $this->formElementErrors($regForm->get('names')); ?>
                            </div>
                            <br>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                <?php echo $this->formElement($regForm->get('phone')->setAttributes(array('class' => 'form-control selectpicker', 'placeholder' => $this->language()->translate('Phone +359')))); ?>
                                <?php echo $this->formElementErrors($regForm->get('phone')); ?>
                            </div>
                            <br>
                            <div><?php echo $this->language()->translate('Please don\'t enter a password if you want to remain unchanged'); ?></div>
                            <br>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                <?php echo $this->formElement($regForm->get('password')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Password')))); ?>
                                <?php echo $this->formElementErrors($regForm->get('password')); ?>
                            </div>
                            <br>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-refresh"></i></span>
                                <?php echo $this->formElement($regForm->get('password_confirm')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Password again')))); ?>
                                <?php echo $this->formElementErrors($regForm->get('password_confirm')); ?>
                            </div>
                            <br>
                            <div><?php echo $this->language()->translate('Logo/Picture');?></div>
                            <br>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-image"></i></span>
                                <?php echo $this->formElement($regForm->get('logo')->setAttributes(array('class' => 'form-control input1'))); ?>
                                <?php echo $this->formElementErrors($regForm->get('logo')); ?>
                            </div>
                            <br>
                            <div id="firmflds">
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <?php echo $this->formElement($regForm->get('director')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Mall'), 'id' => 'director'))); ?>
                                    <?php echo $this->formElementErrors($regForm->get('director')); ?>
                                </div>
                                <br>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <?php echo $this->formElement($regForm->get('vat_number')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('BULSTAT'), 'id' => 'director'))); ?>
                                    <?php echo $this->formElementErrors($regForm->get('vat_number')); ?>
                                </div>
                                <br>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <?php echo $this->formElement($regForm->get('company_address')->setAttributes(array('class' => 'form-control input1', 'placeholder' => mb_strtoupper($this->language()->translate('Address'), 'UTF-8'), 'id' => 'director'))); ?>
                                    <?php echo $this->formElementErrors($regForm->get('company_address')); ?>
                                </div>
                            </div>
                            <br>
                            <br>
                            <script>
                                toggleCompanyUserFields();
                            </script>
                            <input class="submit_button btn btn-primary button2" type="submit" value="<?php echo $this->language()->translate('Save'); ?>" name="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>