<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <div class="page">
                <div class="row">
                    <h2>Вашата регистрация в сайта ogledi.bg е успешна. Благодарим Ви!</h2>
                    <br>
                    Пожелаваме Ви много успешни сделки!<br>
                    <br>
                    Можете да се запознаете подробно с организацията на работата ни като последвате линка “Как работим”.<br>
                </div>
            </div>
        </div>
    </div>
</div>