<?php

$form = $this->form;
/* @var $form \Admin\Form\PricesForm */
$form->prepare();
$form->setAttribute('method', 'post');

$userTypeIdElement = $form->get('user_type_id');
$priceNameElement = $form->get('price_name');
$minOffersElement = $form->get('min_offers');
$maxOffersElement = $form->get('max_offers');
$photoshootPerSqPriceElement = $form->get('photoshoot_per_sq_price');
$photoshootMinPriceElement = $form->get('photoshoot_min_price');
$weeklyPriceElement = $form->get('weekly_price');
$vipPriceElement = $form->get('vip_price');
$topPriceElement = $form->get('top_price');
$chatElement = $form->get('chat');
$priceSchemaElement = $form->get('price_schema');
$submitElement = $form->get('submit')
?>
<h1>Редактиране на цена</h1>
<div class="row">
    <div class="col-md-9 col-lg-">
        <?php echo $this->form()->openTag($form) ?>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($userTypeIdElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $userTypeIdElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($userTypeIdElement);
                echo $this->formElement($userTypeIdElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($userTypeIdElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($userTypeIdElement); ?></div>
            <?php } ?>
        </div>  
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($priceNameElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $priceNameElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($priceNameElement);
                echo $this->formElement($priceNameElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($priceNameElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($priceNameElement); ?></div>
            <?php } ?>
        </div>
               
        <div class="form-group form-elements <?php echo ($this->formElementErrors($minOffersElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $minOffersElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($minOffersElement);
                echo $this->formElement($minOffersElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($minOffersElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($minOffersElement); ?></div>
            <?php } ?>
        </div>
       
        <div class="form-group form-elements <?php echo ($this->formElementErrors($maxOffersElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $maxOffersElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($maxOffersElement);
                echo $this->formElement($maxOffersElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($maxOffersElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($maxOffersElement); ?></div>
            <?php } ?>
        </div>
                
         <div class="form-group form-elements <?php echo ($this->formElementErrors($photoshootPerSqPriceElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $photoshootPerSqPriceElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($photoshootPerSqPriceElement);
                echo $this->formElement($photoshootPerSqPriceElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($photoshootPerSqPriceElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($photoshootPerSqPriceElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($photoshootMinPriceElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $photoshootMinPriceElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($photoshootMinPriceElement);
                echo $this->formElement($photoshootMinPriceElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($photoshootMinPriceElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($photoshootMinPriceElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($weeklyPriceElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $weeklyPriceElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($weeklyPriceElement);
                echo $this->formElement($weeklyPriceElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($weeklyPriceElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($weeklyPriceElement); ?></div>
            <?php } ?>
        </div>
        
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($vipPriceElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $vipPriceElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($vipPriceElement);
                echo $this->formElement($vipPriceElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($vipPriceElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($vipPriceElement); ?></div>
            <?php } ?>
        </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($topPriceElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $topPriceElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($topPriceElement);
                echo $this->formElement($topPriceElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($topPriceElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($topPriceElement); ?></div>
            <?php } ?>
        </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($chatElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $chatElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($chatElement);
                echo $this->formElement($chatElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($chatElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($chatElement); ?></div>
            <?php } ?>
        </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($priceSchemaElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $priceSchemaElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($priceSchemaElement);
                echo $this->formElement($priceSchemaElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($priceSchemaElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($priceSchemaElement); ?></div>
            <?php } ?>
        </div>
        

        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <button id="pricesBack" class="btn btn-success">Назад</button>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script type="text/javascript">    
    
    document.getElementById("pricesBack").onclick = function (event) {
        event.preventDefault(); 
        location.href = '<?php echo $this->url('languageRoute/adminPrices'); ?>';
    };
    
</script>