<?php
$form = $this->form;
/* @var $form \Admin\Form\LoginForm */
$form->prepare();
$form->setAttribute('method', 'post');

$usernameElement = $form->get('username');
$passwordElement = $form->get('password');
$submitElement = $form->get('submit');
?>
<h1>Административен панел - Вход</h1>
<div class="row">
    <div class="col-md-5 col-lg-5">
        <?php echo $this->form()->openTag($form) ?>
        <div
            class="form-group <?php echo ($this->formElementErrors($usernameElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $usernameElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($usernameElement);
                echo $this->formElement($usernameElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($usernameElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($usernameElement); ?></div>
            <?php } ?>
        </div>

        <div class="form-group <?php echo ($this->formElementErrors($passwordElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $passwordElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($passwordElement);
                echo $this->formElement($passwordElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($passwordElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($passwordElement); ?></div>
            <?php } ?>
        </div>

       <!-- <div class="form-group">
            <div class="input-group">
                <div class="g-recaptcha" data-sitekey="6LegGgwUAAAAAHamsJYRMzy_FiVgagOR_NXUP_hK"></div>
            </div>
        </div>
-->
        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>