
<?php
$form = $this->form;
/* @var $form \Admin\Form\ProfileForm */
$form->prepare();
$form->setAttribute('method', 'post');

$username = $form->get('username'); 
$first_name = $form->get('first_name'); 
$last_name = $form->get('last_name');
$password = $form->get('password');
$confirmPassword = $form->get('password_confirm');
$gender = $form->get('gender');
$position = $form->get('position');
$submitElement = $form->get('submit');
?>
<h1>Редактиране на профил</h1>
<div class="row">
    <div class="col-md-5 col-lg-5">
        <?php echo $this->form()->openTag($form) ?>
        
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($first_name) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $first_name->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($first_name);
                echo $this->formElement($first_name->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($first_name)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($first_name); ?></div>
            <?php } ?>
        </div>

        <div class="form-group form-elements <?php echo ($this->formElementErrors($last_name) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $last_name->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($last_name);
                echo $this->formElement($last_name->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($last_name)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($last_name); ?></div>
            <?php } ?>
        </div>       
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($gender) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $gender->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($gender);
                echo $this->formElement($gender->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($gender)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($gender); ?></div>
            <?php } ?>
        </div> 
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($username) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $username->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($username);
                echo $this->formElement($username->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($username)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($username); ?></div>
            <?php } ?>
        </div>                
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($password) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">                     
                <?php
                $password->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($password);
                echo $this->formElement($password->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($password)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($password); ?></div>
            <?php } ?>
        </div>
        
               <div class="form-group form-elements <?php echo ($this->formElementErrors($confirmPassword) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">                     
                <?php
                $confirmPassword->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($confirmPassword);
                echo $this->formElement($confirmPassword->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($confirmPassword)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($confirmPassword); ?></div>
            <?php } ?>
        </div>                        
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($position) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $position->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($position);
                echo $this->formElement($position->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($position)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($position); ?></div>
            <?php } ?>
        </div>
        
                                     

        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <button id="profileBack" class="btn btn-success">Назад</button>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script type="text/javascript">    
    
    document.getElementById("profileBack").onclick = function (event) {
        event.preventDefault(); 
        location.href = '<?php echo $this->url('languageRoute/adminDashboard'); ?>';
    };
</script> 