<h1>Блог</h1>
<button id="createBlog" type="submit" name="submit" class="btn btn-success">Въвеждане на статия</button>

<br>
<br>
<div id="jqxWidget">
    <div id="jqxgrid"></div>
</div>

<script type="text/javascript">
    $(document).ready(function () {    
        
        document.getElementById("createBlog").onclick = function () {
            location.href = '<?php echo $this->url('languageRoute/adminBlogCreate'); ?>';
        };
        
// Show Blog          
        var id = 'id';
        var url = '<?php echo $this->url('languageRoute/adminBlogData'); ?>';            
        var datafields = [
            {name: 'id', type: 'string'},
            {name: 'title', type: 'string'},
            {name: 'description', type: 'string'},
            {name: 'announcement', type: 'string'},
            {name: 'url', type: 'string'},
            {name: 'image', type: 'string'},
            {name: 'position', type: 'int'},
            {name: 'date_published', type: 'date'},
            {name: 'date_created', type: 'date'},
            {name: 'date_updated', type: 'date'},
            {name: 'meta_title', type: 'string'},
            {name: 'meta_description', type: 'string'},
            {name: 'language_id', type: 'int'},
            {name: 'language', type: 'string'},
            {name: 'category_id', type: 'int'},
            {name: 'category', type: 'string'}
        ];
        
        var columns = [
//            {text: 'id', datafield: 'id'},
            {text: 'Дата', datafield: 'date_published', cellsformat: 'd-MM-yyyy HH:mm', width: 150},
            {
                text: 'Снимка', datafield: 'image', width: 120, filterable: false, sortable: false,
                cellsrenderer: function ( row, columnfield, value, defaulthtml, columnproperties ) {      
                    return '<img border="0" height="75" src="/img/blog-img/' + value + '" />';
                }
            },
            {text: 'Заглавие', datafield: 'title'},
//            {text: 'Сайт', datafield: 'url',width: 250},
//            {text: 'description', datafield: 'description'},          
//            {text: 'announcement', datafield: 'announcement'},            
//            {text: 'position', datafield: 'position'},            
//            {text: 'date_created', datafield: 'date_created', cellsformat: 'yyyy-MM-d HH:mm'},            
//            {text: 'date_updated', datafield: 'date_updated', cellsformat: 'yyyy-MM-d HH:mm'},
//            {text: 'meta_title', datafield: 'meta_title'},
//            {text: 'meta_description', datafield: 'meta_description'},
//            {text: 'language_id', datafield: 'language_id'},
//            {text: 'language', datafield: 'language'},
//            {text: 'category_id', datafield: 'category_id'},
            {text: 'Категория', datafield: 'category', width: 150},
            {
                text: '',
                datafield: '',
                width: 84,
                filterable: false,
                sortable: false,
                cellsrenderer: function (row, columnfield, value, defaulthtml, columnproperties) {
                    var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', row);      
                    var deleteURL = '<?php echo $this->url('languageRoute/adminBlogDelete'); ?>/' + dataRecord.id;  
                    return '<button class="btn table-button" style="margin: 3px;" onclick="openDialog(\'' + dataRecord.id + '\')"><i class="fa fa-pencil" aria-hidden="true"></i></button>' + 
                           '<button class="btn confirm-delete" value="' + deleteURL + '"><i class="fa fa-trash" aria-hidden="true"></i></button>';
                }
            },          
        ]; 
        
        dataGrid(id, url, datafields, columns);
        
        //Delete confirmation dialog
        confirmDelete("Are you sure?");
    });

        
// Edit Blog
    function openDialog(langId) {            
        location.href = '<?php echo $this->url('languageRoute/adminBlogEdit'); ?>/' + langId;        
    }
</script>