<?php

$form = $this->form;
/* @var $form \Admin\Form\PagesForm */
$form->prepare();
$form->setAttribute('method', 'post');

$languageIdElement = $form->get('language_id');
$titleElement = $form->get('title');
$descriptionElement = $form->get('description');
$metaTitleElement = $form->get('meta_title');
$metaDescriptionElement = $form->get('meta_description');
$metaKeywordElement = $form->get('meta_keywords');
$submitElement = $form->get('submit');
?>
<h1>Редактиране на страница</h1>
<div class="row">
    <div class="col-md-9 col-lg-9">
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group form-elements <?php echo ($this->formElementErrors($languageIdElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $languageIdElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($languageIdElement);
                echo $this->formElement($languageIdElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($languageIdElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($languageIdElement); ?></div>
            <?php } ?>
        </div>

        
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($titleElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $titleElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($titleElement);
                echo $this->formElement($titleElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($titleElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($titleElement); ?></div>
            <?php } ?>
        </div>
        
        
         <div class="form-group form-elements<?php echo ($this->formElementErrors($descriptionElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $descriptionElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($descriptionElement);
                echo $this->formElement($descriptionElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($descriptionElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($descriptionElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($metaTitleElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $metaTitleElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($metaTitleElement);
                echo $this->formElement($metaTitleElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($metaTitleElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($metaTitleElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($metaDescriptionElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $metaDescriptionElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($metaDescriptionElement);
                echo $this->formElement($metaDescriptionElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($metaDescriptionElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($metaDescriptionElement); ?></div>
            <?php } ?>
        </div>
        
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($metaKeywordElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $metaKeywordElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($metaKeywordElement);
                echo $this->formElement($metaKeywordElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($metaKeywordElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($metaKeywordElement); ?></div>
            <?php } ?>
        </div>

        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <button id="pagesBack" class="btn btn-success">Назад</button>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script>
    tinymce.init({
        selector: '#description',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table contextmenu paste code'
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'
    });
</script>

<script type="text/javascript">    
    
    document.getElementById("pagesBack").onclick = function (event) {
        event.preventDefault(); 
        location.href = '<?php echo $this->url('languageRoute/adminPages'); ?>';
    };
    
</script>