<?= $this->doctype() ?>
<?php
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Огледи БГ - Административен Панел')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/jqx.light.css'))
            ->prependStylesheet($this->basePath('css/jqx.base.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/tinymce/tinymce.min.js'))
            ->prependFile($this->basePath('js/script.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jqx-all.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('languageRoute/adminLogin') ?>">
                        <img src="<?= $this->basePath('img/logo_ogledi.png') ?>" height="28" />
                    </a>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>ОГЛЕДИ БГ &copy; <?= date('Y') ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
