<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <?php if(!empty($this->layout()->metaTitle)) { ?>    
            <meta name="title" content="<?php echo $this->layout()->metaTitle; ?>">
            <title><?php echo $this->layout()->metaTitle; ?> - Ogledi.BG</title>
        <?php } else { ?>
            <meta name="title" content="OglediBG">
            <title>Ogledi.BG</title>
        <?php } ?>
        
        <?php if(!empty($this->layout()->metaDescription)) { ?>    
        <meta name="description" content="<?php echo $this->layout()->metaDescription; ?>">
        <?php } else { ?>
        <meta name="description" content="OglediBG">
        <?php } ?>  
        
        <?php if(!empty($this->layout()->metaKeywords)) { ?>    
        <meta name="keywords" content="<?php echo $this->layout()->metaKeywords; ?>">
        <?php } else { ?>
        <meta name="keywords" content="OglediBG">
        <?php } ?>
            
        <?php if(!empty($this->layout()->metaTags)) {
                foreach ($this->layout()->metaTags as $key => $value ) {
                    echo '<meta property="' . $key . '" content="' . $value . '" />';
                }
        } ?> 

        
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <link rel="shortcut icon" href="/favicon.ico"/>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-multiselect.css">
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <link rel="stylesheet" href="/css/theme.css?v=29">
        <link rel="stylesheet" href="/css/sweetalert.css">
        <link rel="stylesheet" href="/css/owl.carousel.min.css">
        <link rel="stylesheet" href="/css/jquery.datetimepicker.min.css">
        <link rel="stylesheet" href="/css/fancybox/jquery.fancybox.css">
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="/js/main.js?v=21"></script>
        <script src="/js/bootstrap-multiselect.js"></script>
        <script src="/js/sweetalert.min.js"></script>
        <script src="/js/owl.carousel.min.js"></script>
        <script src="/js/jquery.datetimepicker.full.min.js"></script>
        <script src="/js/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
        <script src="https://apis.google.com/js/plusone.js"></script>

        <!-- Gemius Code -->
        <script type="text/javascript" src="/js/gemius.js"></script>

        <!-- Facebook Pixel Code -->
        <script>
            !function (f, b, e, v, n, t, s) {
                if (f.fbq)
                    return;
                n = f.fbq = function () {
                    n.callMethod ?
                            n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                };
                if (!f._fbq)
                    f._fbq = n;
                n.push = n;
                n.loaded = !0;
                n.version = '2.0';
                n.queue = [];
                t = b.createElement(e);
                t.async = !0;
                t.src = v;
                s = b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t, s)
            }(window,
                    document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '327945034256784'); // Insert your pixel ID here.
            fbq('track', 'PageView');
        </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=327945034256784&ev=PageView&noscript=1" /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->

</head>
<body>    
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[ 0 ];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=173691695996474";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="body">
        <!-- Start Site Header -->
        <header class="site-header" id="top">
            <div class="top-header hidden-xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6">
                            <div class="horiz-nav pull-left">
                                <div class="dropdown">
                                    <?php if ($this->auth()->getService()->hasIdentity()) { ?>
                                        <a href="<?php echo $this->url('languageRoute/myProfile', array('lang' => $_SESSION['lang'])); ?>"><i class="fa fa-user"></i><?php echo $this->language()->translate('My profile'); ?></a>
                                        <a href="<?php echo $this->url('languageRoute/myLogout', array('lang' => $_SESSION['lang'])); ?>"><i class="fa fa-sign-out"></i><?php echo $this->language()->translate('Exit'); ?></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->url('languageRoute/login', array('lang' => $_SESSION['lang'])); ?>"><i class="fa fa-user"></i><?php echo $this->language()->translate('Enter/Register'); ?></a>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-sm-6">
                            <div class="horiz-nav pull-right">
                                <!--change language options-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="middle-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-8 col-xs-8">
                            <div class="logo">
                                <a href="/" title="Начало">
                                    <img src="/img/ogledi.png" alt="Ogledi.bg">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8 col-sm-4 col-xs-4">
                            <div class="contact-info-blocks hidden-sm hidden-xs">
                                <span id="bg" class="btn-language" value="bg"><img class="btn-language-margin" src="/img/bulgarianflag.png"></span>
                                <span id="en" class="btn-language" value="en"><img class="btn-language-margin" src="/img/englishflag.png"></span>
                                <div id="mibew-container">
                                    <div>
                                        <a href="/<?php echo $_SESSION['lang'];?>/contacts"><i class="fa fa-envelope fa-2x"></i> <?php echo $this->language()->translate('Write us'); ?></a>
                                    </div>
                                </div>
                            </div>
                            <a href="#" class="visible-sm visible-xs menu-toggle" style="text-transform:uppercase; text-decoration:none; color:red;">
                                <i class="fa fa-bars"></i><?php echo $this->language()->translate('Menu'); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="main-menu-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <nav class="navigation">
                                <ul id="menu-main-menu" class="sf-menu">
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-240 hide-mobile-menu mobile-menu-item" style="padding: 0px 19px;">
                                        <span id="bg" class="btn-language" value="bg"><img src="/img/bulgarianflag.png"></span>
                                        <span id="en" class="btn-language" value="en"><img src="/img/englishflag.png"></span>
                                    </li>
                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children">
                                        <a href="<?php echo $this->url('languageRoute/search', array('lang' => $_SESSION['lang'])); ?>"><i class="fa fa-search"></i><?php echo $this->language()->translate('Search'); ?> </a>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-225">
                                        <?php if ($_SESSION['lang'] == 'bg'): ?>
                                            <a href="/<?php echo $_SESSION['lang']; ?>/info/КАК-РАБОТИМ"><?php echo $this->language()->translate('Как работим'); ?></a>
                                        <?php else : ?>
                                            <a href="/<?php echo $_SESSION['lang']; ?>/info/How-we-work"><?php echo $this->language()->translate('How we work'); ?></a>
                                        <?php endif; ?>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-283">
                                        <?php if ($this->auth()->getService()->hasIdentity()) { ?>
                                            <a href="<?php echo $this->url('languageRoute/myOffersCreate', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Property for filming'); ?></a>
                                        <?php } else { ?>
                                            <a href="<?php echo $this->url('languageRoute/login', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Property for filming'); ?></a>
                                        <?php } ?>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-283">
                                        <?php if ($this->auth()->getService()->hasIdentity()) { ?>
                                            <a href="<?php echo $this->url('languageRoute/myOffersCreate', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Place your ad'); ?></a>
                                        <?php } else { ?>
                                            <a href="<?php echo $this->url('languageRoute/login', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Place your ad'); ?></a>
                                        <?php } ?>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-227 dropdown" >
                                        <a href="<?php echo $this->url('languageRoute/blog', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Blog'); ?></a>
                                        <div class="dropdown-content">
                                            <?php foreach ($this->layout()->blogCategory as $key => $category) { ?>
                                                <a href="<?php echo $this->url('languageRoute/blog-category', array('lang' => $_SESSION['lang'], 'id' => $key)); ?>"><?php echo $this->language()->translate($category); ?></a>
                                            <?php } ?>
                                        </div>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-227 dropdown" >
                                        <a href="<?php echo $this->url('languageRoute/service', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Other 360 tours'); ?></a>
                                        <div class="dropdown-content">
                                            <?php foreach ($this->layout()->serviceCategory as $key => $category) { ?>
                                                <a href="<?php echo $this->url('languageRoute/service-category', array('lang' => $_SESSION['lang'], 'id' => $key)); ?>"><?php echo $this->language()->translate($category); ?></a>
                                            <?php } ?>
                                        </div>
                                    </li>

                                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-225">
                                        <?php if ($_SESSION['lang'] == 'bg'): ?>
                                            <a href="/<?php echo $_SESSION['lang']; ?>/info/ceni"><?php echo $this->language()->translate('Service'); ?></a>
                                        <?php else : ?>
                                            <a href="/<?php echo $_SESSION['lang']; ?>/info/Prices"><?php echo $this->language()->translate('Service'); ?></a>
                                        <?php endif; ?>
                                    </li>

                                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-240">
                                        <a href="<?php echo $this->url('languageRoute/contacts', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Contact'); ?></a>
                                    </li>

                                    <?php if ($this->auth()->getService()->hasIdentity()) { ?>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-240 mobile-menu-item"><a href="<?php echo $this->url('languageRoute/myProfile', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('My profile'); ?></a></li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-240 mobile-menu-item"><a href="<?php echo $this->url('languageRoute/myLogout', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Exit'); ?></a></li>
                                    <?php } else { ?>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-240 mobile-menu-item"><a href="<?php echo $this->url('languageRoute/login', array('lang' => $_SESSION['lang'])); ?>"><?php echo $this->language()->translate('Enter/Register'); ?></a></li>
                                    <?php } ?>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- End Site Header -->

        <?php echo $this->content ?>
        <div id="banner-left">
            <script type='text/javascript'><!--//<![CDATA[
                    var m3_u = (location.protocol == 'https:' ? 'https://ads.ogledi.bg/www/delivery/ajs.php' : 'http://ads.ogledi.bg/www/delivery/ajs.php');
                var m3_r = Math.floor(Math.random() * 99999999999);
                if (!document.MAX_used)
                    document.MAX_used = ',';
                document.write("<scr" + "ipt type='text/javascript' src='" + m3_u);
                document.write("?zoneid=5");
                document.write('&amp;cb=' + m3_r);
                if (document.MAX_used != ',')
                    document.write("&amp;exclude=" + document.MAX_used);
                document.write(document.charset ? '&amp;charset=' + document.charset : (document.characterSet ? '&amp;charset=' + document.characterSet : ''));
                document.write("&amp;loc=" + escape(window.location));
                if (document.referrer)
                    document.write("&amp;referer=" + escape(document.referrer));
                if (document.context)
                    document.write("&context=" + escape(document.context));
                if (document.mmm_fo)
                    document.write("&amp;mmm_fo=1");
                document.write("'><\/scr" + "ipt>");
                //]]>--></script><noscript><a href='http://ads.ogledi.bg/www/delivery/ck.php?n=a695a145&amp;cb=(new Date().getTime())' target='_blank'><img src='http://ads.ogledi.bg/www/delivery/avw.php?zoneid=5&amp;cb=(new Date().getTime())&amp;n=a695a145' border='0' alt='' /></a></noscript>
        </div>
        <div id="banner-right">
            <script type='text/javascript'><!--//<![CDATA[
                var m3_u = (location.protocol == 'https:' ? 'https://ads.ogledi.bg/www/delivery/ajs.php' : 'http://ads.ogledi.bg/www/delivery/ajs.php');
                var m3_r = Math.floor(Math.random() * 99999999999);
                if (!document.MAX_used)
                    document.MAX_used = ',';
                document.write("<scr" + "ipt type='text/javascript' src='" + m3_u);
                document.write("?zoneid=4");
                document.write('&amp;cb=' + m3_r);
                if (document.MAX_used != ',')
                    document.write("&amp;exclude=" + document.MAX_used);
                document.write(document.charset ? '&amp;charset=' + document.charset : (document.characterSet ? '&amp;charset=' + document.characterSet : ''));
                document.write("&amp;loc=" + escape(window.location));
                if (document.referrer)
                    document.write("&amp;referer=" + escape(document.referrer));
                if (document.context)
                    document.write("&context=" + escape(document.context));
                if (document.mmm_fo)
                    document.write("&amp;mmm_fo=1");
                document.write("'><\/scr" + "ipt>");
                //]]>--></script><noscript><a href='http://ads.ogledi.bg/www/delivery/ck.php?n=a2319d03&amp;cb=(new Date().getTime())' target='_blank'><img src='http://ads.ogledi.bg/www/delivery/avw.php?zoneid=4&amp;cb=(new Date().getTime())&amp;n=a2319d03' border='0' alt='' /></a></noscript>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        </div>

        <!-- Start Site Footer -->
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 widget footer-widget widget_latest_news">
                        <h3 class="widgettitle"><?php echo $this->language()->translate('Information'); ?></h3>
                        <?php
                        $pages = $this->pages()->getPagesArray();
                        if (count($pages) > 0) {
                            for ($i = 0; $i < 5; $i++) {
                                $page = $pages[$i];
                                ?>
                                <div class="menu-useful-links-container">
                                    <ul id="menu-useful-links" class="menu">
                                        <li>
                                            <a href="<?php echo $this->url('languageRoute/info', array('lang' => $_SESSION['lang'], 'url' => $page['url'])); ?>" title="<?php echo mb_strtoupper($page['title'], 'UTF-8'); ?>"><?php echo mb_strtoupper($page['title'], 'UTF-8'); ?> </a>
                                        </li>
                                    </ul>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="col-md-3 col-sm-3 widget footer-widget widget_nav_menu">
                        <h3 class="widgettitle">&nbsp;</h3>
                        <?php
                        $pages = $this->pages()->getPagesArray();
                        if (count($pages) > 0) {
                            for ($i = 5; $i < count($pages); $i++) {
                                $page = $pages[$i];
                                ?>
                                <div class="menu-useful-links-container">
                                    <ul id="menu-useful-links" class="menu">
                                        <li>
                                            <a href="<?php echo $this->url('languageRoute/info', array('lang' => $_SESSION['lang'], 'url' => $page['url'])); ?>" title="<?php echo mb_strtoupper($page['title'], 'UTF-8'); ?>"><?php echo mb_strtoupper($page['title'], 'UTF-8'); ?> </a>
                                        </li>
                                    </ul>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="col-md-3 col-sm-3 widget footer-widget widget_twitter_feeds">
                        <h3 class="widgettitle"><?php echo mb_strtoupper($this->language()->translate('Follow us'), 'UTF-8'); ?></h3>
                        <!--fb-->
                        <div class="fb-page" data-href="https://www.facebook.com/Ogledibg-298858123780068/"
                             data-tabs="timeline" data-height="250" data-small-header="true"
                             data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                            <div class="fb-xfbml-parse-ignore">
                                <blockquote cite="https://www.facebook.com/Ogledibg-298858123780068/">
                                    <a href="https://www.facebook.com/Ogledibg-298858123780068/"><?php echo $this->language()->translate('Site Url'); ?></a>
                                </blockquote>
                            </div>
                        </div>
                        <!--/fb-->
                    </div>
                    <div class="col-md-3 col-sm-3 widget footer-widget widget_newsletter">
                        <h3 class="widgettitle"><?php echo $this->language()->translate('Sign up for Newsletter'); ?></h3>
                        <p><?php echo $this->language()->translate('Sign up for Newsletter info'); ?></p>
                        <form method="post" action="<?php echo $this->url('languageRoute/newsletter', array('lang' => $_SESSION['lang']));  ?>" name="newsletter_form">
                            <input type="email" name="suber" id="suber" placeholder="<?php echo $this->language()->translate('Real e-mail'); ?>" class="form-control">
                            <div id="nwermsg" style="display: none; color:red;">Моля въведете валиден е-майл!</div>
                            <input type="submit" name="newsletter_submit" class="btn btn-primary btn-block btn-lg"
                                   value="<?php echo $this->language()->translate('Save me'); ?>">
                        </form>
                        <br>
                        <div class="social-icons">
                            <a style="font-size: 1.9em; color: #3B5998; margin-left:1px;"
                               href="https://www.facebook.com/Ogledibg-298858123780068/" target="_blank">
                                <i class="fa fa-facebook-official"></i>
                            </a>
                            <a style="font-size: 1.9em; color: #3B5998; margin-left:1px;"
                               href="https://www.instagram.com/ogledibg/" target="_blank">
                                <i class="fa fa-instagram"></i>
                            </a>
                            <a style="font-size: 1.9em; color: red; margin-left:1px;"
                               href="https://www.youtube.com/channel/UCyU_6iKUDBbt_PDPkK9N-FQ" target="_blank">
                                <i class="fa fa-youtube"></i>
                            </a>
                            <a style="font-size: 1.9em; color:#4885ed;" href="https://plus.google.com/+OglediBg" target="_blank">
                                <i class="fa fa-google-plus"></i>
                            </a>
                            <a style="font-size: 1.9em; color:red;" href="https://www.pinterest.com/ogledibg/"
                               target="_blank">
                                <i class="fa fa-pinterest"></i>
                            </a>
                            <a style="font-size: 1.9em; color: #4099FF;" href="https://twitter.com/ogledibg"
                               target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <footer class="site-footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="copyrights-col-left col-md-6 col-sm-6">
                        <a href="#top" id="btngotop">TOP</a>
                        <p>&copy; <?= date('Y') ?><?php echo $this->language()->translate('Footer'); ?></p>
                    </div>
                </div>
            </div>
        </footer>
    </div>   


    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>

    <script>
                $(".btn-language").click(function () {
                    var languageValue = $(this).attr('value');

                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->url('languageRoute/changeLanguage'); ?>',
                        data: {"lang": languageValue},
                        success: function (data) {
                            if (data.return == 'success')
                            {
                                var pathname = window.location.pathname; // Returns path only     
                                if (pathname !== '/')
                                {
                                    var partOne = pathname.split(/\/(.+)/)[1];
                                    var partTwo = partOne.split(/\/(.+)/)[1];
                                    var partThree = '/' + data.lang + '/' + partTwo;
                                    var newUrl = 'http://' + document.domain + partThree;
                                    window.location.replace(newUrl);
                                } else {
                                    location.reload();
                                }
                            }
                        }
                    });
                });
    </script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-82648529-1', 'auto');
        ga('send', 'pageview');

    </script>

    <img src="//as.adwise.bg/servlet/tp.gif?id=1376" width="1px" height="1px" style="display:none;">

</body>
</html>