<?php
$dashboardFilterForm->prepare();
echo $this->form()->openTag($dashboardFilterForm);

$cityElement = $dashboardFilterForm->get('city_id');
$periodElement = $dashboardFilterForm->get('period_id');
$dateFrom = $dashboardFilterForm->get('date_from');
$dateTo = $dashboardFilterForm->get('date_to');
$submitElement = $dashboardFilterForm->get('submit')
?>
<h1></h1>
<div class="row">
    <div class="col-md-9 col-lg-">
        <?php echo $this->form()->openTag($dashboardFilterForm) ?>

        <div class="form-group form-elements <?php echo ($this->formElementErrors($cityElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $cityElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($cityElement);
                echo $this->formElement($cityElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($cityElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($cityElement); ?></div>
            <?php } ?>
        </div>
        <div class="clearfix">
            <input style="float: left" type="radio" name="period_type" value="period" checked="checked"/>
            <div style="width: 35px;float: left;padding: 10px; margin-right: 30px"><?php echo 'Период'; ?></div>
            <div class="dashboard-period-div">                                                       
                <?php echo $this->formRow($dashboardFilterForm->get('period_id')->setAttribute('class', 'form-control text-input'), null, false); ?>     
            </div>
        </div>        
        <div class="clearfix">
            <input style="float: left" type="radio" name="period_type" value="date" />
            <div class="dashboard-date-from"><?php echo 'От'; ?></div>
            <div class="dashboard-date-div">                                                       
                <?php echo $this->formRow($dashboardFilterForm->get('date_from')->setAttribute('class', 'form-control text-input'), null, false); ?>     
            </div>
            <div class="dashboard-date-to"><?php echo 'До'; ?></div>    
            <div class="dashboard-date-div">                                            
                <?php echo $this->formRow($dashboardFilterForm->get('date_to')->setAttribute('class', 'form-control text-input'), null, false); ?>
            </div>
        </div>
        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success dashboard-submit')) ?>
        <input type="button" class="btn btn-info dashboard-date-clear" value="Изчисти"/>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#dashboardFilterForm').submit(function (e) {
            e.preventDefault();
            $('#jqxgrid').jqxGrid('updatebounddata');
        });

        $('#jqxgrid').jqxGrid({sortable: false});
        $('.dashboard-submit').one('click', function () {
            $('#jqxgrid').jqxGrid({sortable: true});
        });


        var dateFromFilter = '<?php echo $filters['date_from']; ?>';
        if (dateFromFilter !== '') {
            $('#date_from').val(dateFromFilter);
        }

        var dateToFilter = '<?php echo $filters['date_to']; ?>';
        if (dateToFilter !== '') {
            $('#date_to').val(dateToFilter);
        }


        $('#date_from').click(function () {
            var dateFromFilter = '<?php echo $filters['date_from']; ?>';
            if (dateFromFilter !== '') {
                TransactionsDateTimePicker('#date_from', dateFromFilter);
            } else {
                TransactionsDateTimePicker('#date_from');
            }
        });

        $('#date_to').click(function () {
            var dateToFilter = '<?php echo $filters['date_to']; ?>';
            if (dateToFilter !== '') {
                TransactionsDateTimePicker('#date_to', dateToFilter);
            } else {
                TransactionsDateTimePicker('#date_to');
            }
        });

        $('.dashboard-date-clear').click(function () {
            window.location.href = location.href;
        });
    });

</script>