<h1>Без панорами</h1>
<div id="ajax-result"></div>

<br>
<div id="jqxWidget">
    <div id="jqxgrid"></div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        var id = 'id';
        var url = '<?php echo $this->url('languageRoute/adminNoPanoramasData'); ?>';
        var datafields = [
            {name: 'id', type: 'int'},
//            {name: 'title', type: 'string'},
//            {name: 'description', type: 'string'},
//            {name: 'top_offer', type: 'string'},
//            {name: 'vip_offer', type: 'string'},
            {name: 'price', type: 'string'},
//            {name: 'currency_id', type: 'string'},
//            {name: 'construction_year', type: 'string'},
            {name: 'area', type: 'string'},
//            {name: 'floor', type: 'string'},
//            {name: 'bathrooms', type: 'string'},
//            {name: 'total_rooms', type: 'string'},
//            {name: 'parking_slots', type: 'string'},
//            {name: 'information', type: 'string'},
//            {name: 'photographer_address', type: 'string'},
            {name: 'photographerAppointment', type: 'string'},
//            {name: 'youtube_code_1', type: 'string'},
//            {name: 'youtube_code_2', type: 'string'},
//            {name: 'google_360', type: 'string'},
//            {name: 'panorama_file', type: 'string'},
//            {name: 'garden', type: 'string'},
//            {name: 'meta_title', type: 'string'},
//            {name: 'meta_description', type: 'string'},
//            {name: 'meta_keywords', type: 'string'},
            {name: 'dateCreated', type: 'date'},
//            {name: 'date_updated', type: 'date'},
//            {name: 'language_id', type: 'string'},
            {name: 'offerStatusName', type: 'string'},
//            {name: 'offer_type_id', type: 'string'},
//            {name: 'buildingTypeName', type: 'string'},
            {name: 'propertyTypeName', type: 'string'},
//            {name: 'heating_system_id', type: 'string'},
//            {name: 'user_id', type: 'string'},
            {name: 'neighbourhoodName', type: 'string'},
            {name: 'cityName', type: 'string'},
//            {name: 'street', type: 'string'},
//            {name: 'lat', type: 'string'},
//            {name: 'lng', type: 'string'}

        ];

        var columns = [
            {text: '№', datafield: 'id', width: 50,
                cellsrenderer: function ( row, columnfield, value, defaulthtml, columnproperties ) {
                    return '<div style="overflow: hidden; text-overflow: ellipsis; padding-bottom: 2px; text-align: left; margin-right: 2px; margin-left: 4px; margin-top: 10px;"><a href="offers-edit/' + value + '">' + value + '</a></div>';
                }},
            {text: 'Вид имот', datafield: 'propertyTypeName'},
            {text: 'Град', datafield: 'cityName', width: 100},
            {text: 'Квартал', datafield: 'neighbourhoodName', width: 250},
            {text: 'Цена', datafield: 'price'},
            {text: 'Площ (кв.м.)', datafield: 'area', width: 130},
//            {text: 'Конструкция', datafield: 'buildingTypeName', width: 100},
            {text: 'Дата на въвеждане', datafield: 'dateCreated', width: 150, cellsformat: 'd-MM-yyyy HH:mm'},
            {text: 'Дата и час на заснемане', datafield: 'photographerAppointment', width: 200, cellsformat: 'dd-MM-yyyy HH:mm', 
                cellsrenderer: function (row, columnfield, value, defaulthtml, columnproperties) {  
                    //1000ms * 60s * 60min * 24h * 3d
                    if (new Date().getTime() - new Date(value).getTime() > 1000*60*60*24*3) {                        
                        return '<div style="padding: 10px; background-color: red; color: white">' + value + '</div>';
                    } else {
                        return '<div style="padding: 10px;">' + value + '</div>';
                    }                   
                }
            },

        ];

        dataGrid(id, url, datafields, columns);

        //Delete confirmation dialog
        confirmDelete("Are you sure?");

    });
</script>

