<!-- Site Showcase -->
<section class="module parallax parallax-5" style="height: 120px;">
    <div class="container">        
    </div>
</section>
<!-- End Showcase -->
<!-- Start Content -->
<div class="main" role="main">
  <div id="content" class="content full">
    <div class="container">     
        <div class="col-md-12">   
            </br>
            <p style="font-size: 20px;"><?php echo $this->language()->translate('Thank you contacts'); ?></p>
        </div>            
    </div>
  </div>
</div>