<?php
$contactForm = $this->contactForm;
$contactForm->prepare();
?>
<!-- Site Showcase -->
<section class="module parallax parallax-8" style="height: 120px;">
    <div class="container">
        <h2><?php echo $this->language()->translate('Contact'); ?></h2>
    </div>
</section>
<!-- End Showcase -->
<!-- Start Content -->
<div class="main" role="main">
  <div id="content" class="content full">
    <span class="property_zoom_level" id="4"></span>
    <div class="container">
      <div class="page">
        <div class="row">
          <div class="col-md-6 col-sm-6">
            <h3><?php echo $this->language()->translate('Feedback form'); ?></h3>
                <?php echo $this->form()->openTag($contactForm) ?>
                  <input type="hidden" name="loginForm" value="1" />
                  <div class="input-group"><span class="input-group-addon"><i class="fa fa-square"></i></span>
                        <?php echo $this->formElement($contactForm->get('name')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Name Surname*')))); ?>  
                    </div>
                    <?php if ($this->formElementErrors($contactForm->get('name'))) { ?>
                        <div class="alert alert-danger"><?php echo $this->formElementErrors($contactForm->get('name')); ?></div>
                    <?php } ?>           
                    <br>
                    
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <?php echo $this->formElement($contactForm->get('email')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('E-mail*')))); ?>
                    </div>
                    <?php if ($this->formElementErrors($contactForm->get('email'))) { ?>
                        <div class="alert alert-danger"><?php echo $this->formElementErrors($contactForm->get('email')); ?></div>
                    <?php } ?>
                    <br>
                    
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-phone"></i></span>
                        <?php echo $this->formElement($contactForm->get('phone')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Phone')))); ?>
                    </div>
                    <?php if ($this->formElementErrors($contactForm->get('phone'))) { ?>
                        <div class="alert alert-danger"><?php echo $this->formElementErrors($contactForm->get('phone')); ?></div>
                    <?php } ?>
                    <br>
                    
                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-square"></i></span>
                        <?php echo $this->formElement($contactForm->get('frmsmbx')->setAttributes(array('class' => 'form-control input1', 'placeholder' => $this->language()->translate('Message')))); ?>
                    </div>
                    <?php if ($this->formElementErrors($contactForm->get('frmsmbx'))) { ?>
                        <div class="alert alert-danger"><?php echo $this->formElementErrors($contactForm->get('frmsmbx')); ?></div>
                    <?php } ?>
                    <br>

              <div class="input-group">
                  <div class="g-recaptcha" data-sitekey="6LegGgwUAAAAAHamsJYRMzy_FiVgagOR_NXUP_hK"></div>
              </div>
              <?php if ($this->loginFormError) { ?>
                  <div class="alert alert-danger"><?php echo $this->loginFormError; ?></div>
              <?php } ?>
                    <br>
                    <input class="submit_button btn btn-primary button2" type="submit" value="<?php echo $this->language()->translate('Send'); ?>" name="submit">
                    <br clear="all">
                <?php echo $this->form()->closeTag() ?>
            <div class="clearfix"></div>
            <div id="message"></div>
          </div>
          <div class="col-md-6 col-sm-6">
            <h3><?php echo $this->language()->translate('Our office'); ?></h3>
            <div class="padding-as25 lgray-bg">
 <p><?php echo $this->language()->translate('Our office Country and Town'); ?>  
  <br> <?php echo $this->language()->translate('Our office Address'); ?>
 </p>
                <p>e-mail:
                    <a href="mailto:<?php echo $this->language()->translate('Our office mail'); ?>">
                        <strong><?php echo $this->language()->translate('Our office mail'); ?></strong>
                    </a>
                    <?php echo $this->language()->translate('Or call'); ?>
                    <strong><a href="tel:<?php echo $this->language()->translate('Our office number'); ?>"><br>
                            <?php echo $this->language()->translate('Our office number'); ?></a></strong>
                </p>
 <div id="contact51" class="property_container">
 </div>
</div>
            <div class="share-bar">

            </div>
          </div>
          <hr>

<div class="col-md-12">
<h3><?php echo $this->language()->translate('Location'); ?></h3>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2932.65699843155!2d23.32912771503822!3d42.68980752220674!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa8574d1290519%3A0x112edb62f4d9438f!2sul.+%22General+Yosif+V.+Gourko%22+62-%D0%90%2C+1142+Sofia!5e0!3m2!1sen!2sbg!4v1466859456614" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

        </div>
      </div>
    </div>
  </div>
</div>
