<!-- Site Showcase -->
<section class="module parallax parallax-9" style="height: 120px;">
    <div class="container">
        <h2><?php echo $this->language()->translate($categoryName['name']); ?></h2>
    </div>
</section>
<!-- End Showcase -->
<!-- Start Content -->
<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <?php
            $left = $middle = $right = [];
            for ($i = 0; $i < $this->count; $i++) {
                if ($i % 3 == 0) {
                    $left[] = $i;
                } elseif ($i % 3 == 1) {
                    $middle[] = $i;
                } elseif ($i % 3 == 2) {
                    $right[] = $i;
                }
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="property-grid">
                        <?php if ($this->count > 0) { ?>                        
                            <div style="width: 100%; float: left;">
                                <ul class="paginationX desktop-show">
                                    <?php if ($this->page == 1) { ?>
                                        <li class="btn btn-default" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li><a class="btn btn-default" href="?page=1">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</a></li>
                                    <?php } ?>
                                    <?php for ($i = 1; $i <= $this->maxPages; $i++) { ?>
                                        <?php if ($this->page == $i) { ?>
                                            <li class="btn btn-default" style="background:#ccc;"><span>&nbsp;<?php echo $i; ?>&nbsp;</span></li>
                                        <?php } else { ?>
                                            <li><a href="?page=<?php echo $i; ?>" class="btn btn-default" >&nbsp;<?php echo $i; ?>&nbsp;</a></li>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php if ($this->page == $this->maxPages) { ?>
                                        <li class="btn btn-default" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li><a class="btn btn-default" href="?page=<?php echo $this->maxPages; ?>">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</a></li>
                                    <?php } ?>                                 
                                </ul>                                                                
                            </div>
                            <div>
                                <ul class="paginationX mobile-show">
                                    <?php if ($this->page == 1) { ?>
                                        <li class="btn btn-default paginationX-first" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li class="paginationX-first"><a class="btn btn-default" href="?page=1">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</a></li>
                                    <?php } ?>

                                    <?php if ($this->page == $this->maxPages) { ?>
                                        <li class="btn btn-default paginationX-last" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li class="paginationX-last"><a class="btn btn-default" href="?page=<?php echo $this->maxPages; ?>">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</a></li>
                                    <?php } ?>                                   
                                    <br>&nbsp;
                                    <br>&nbsp;
                                    <?php for ($i = 1; $i <= $this->maxPages; $i++) { ?>
                                        <?php if ($this->page == $i) { ?>
                                            <li class="btn btn-default paginationX-middle" style="background:#ccc;"><span>&nbsp;<?php echo $i; ?>&nbsp;</span></li>
                                        <?php } else { ?>
                                            <li><a href="?page=<?php echo $i; ?>" class="btn btn-default paginationX-middle" >&nbsp;<?php echo $i; ?>&nbsp;</a></li>
                                        <?php } ?>
                                    <?php } ?>
                                </ul>
                            </div>
                            <br>&nbsp;
                            <br>&nbsp;                            
                            <div class="clearfix">
                                <div class="column-news col-md-4">
                                    <ul class="grid-holder col-1 isotope" style="position: relative; overflow: hidden; ">
                                        <?php foreach ($this->serviceArticles as $key => $service): ?>                
                                            <?php foreach ($left as $leftelements): ?>                
                                                <?php if ($key == $leftelements): ?>                                        
                                                    <li class="grid-item post format-link isotope-item" >
                                                        <div class="isotopeNews-item" style="float: left;">                            
                                                            <a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>" class="media-box" title="<?php echo $service['title']; ?>">
                                                                <img src="/img/service-img/<?php echo $service['id'];?>/<?php echo $service['image']; ?>" 
                                                                     alt="Ogledi.bg"                                                     
                                                                     >
                                                                <span class="zoom" style="width: 354; height: 100%; line-height: 218px;"></span>
                                                            </a>
                                                            <div class="grid-content">
                                                                <h4><a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>"><?php echo $service['title']; ?></a></h4>
                                                                <span class="meta-data"><span><i class="fa fa-calendar"></i><?php echo $service['date_published']; ?></span></span>
                                                                <p><?php echo mb_substr(strip_tags($service['description']), 0, 80, 'utf-8'); ?></p>
                                                            </div>
                                                        </div>
                                                    </li>
                                                <?php endif; ?>
                                            <?php endforeach; ?>                                
                                        <?php endforeach; ?>
                                    </ul>            
                                </div>

                                <div class="column-news col-md-4">
                                    <ul class="grid-holder col-1 isotope" style="position: relative; overflow: hidden; ">
                                        <?php foreach ($this->serviceArticles as $key => $service): ?>                
                                            <?php foreach ($middle as $middleelements): ?>                
                                                <?php if ($key == $middleelements): ?>                        
                                                    <li class="grid-item post format-link isotope-item" >
                                                        <div class="isotopeNews-item" style="float: left;">                            
                                                            <a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>" class="media-box" title="<?php echo $service['title']; ?>">
                                                                <img src="/img/service-img/<?php echo $service['id'];?>/<?php echo $service['image']; ?>"                                                          
                                                                     alt="Ogledi.bg"                              
                                                                     >
                                                                <span class="zoom" style="width: 354; height: 100%; line-height: 218px;"></span>
                                                            </a>
                                                            <div class="grid-content">
                                                                <h4><a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>"><?php echo $service['title']; ?></a></h4>
                                                                <span class="meta-data"><span><i class="fa fa-calendar"></i><?php echo $service['date_published']; ?></span></span>
                                                                <p><?php echo mb_substr(strip_tags($service['description']), 0, 80, 'utf-8'); ?></p>
                                                            </div>
                                                        </div>
                                                    </li>
                                                <?php endif; ?>
                                            <?php endforeach; ?>                                
                                        <?php endforeach; ?>
                                    </ul>            
                                </div>

                                <div class="column-news col-md-4">
                                    <ul class="grid-holder col-1 isotope" style="position: relative; overflow: hidden; ">
                                        <?php foreach ($this->serviceArticles as $key => $service): ?>                
                                            <?php foreach ($right as $rightelements): ?>                
                                                <?php if ($key == $rightelements): ?>                        
                                                    <li class="grid-item post format-link isotope-item" >
                                                        <div class="isotopeNews-item" style="float: left;">                            
                                                            <a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>" class="media-box" title="<?php echo $service['title']; ?>">
                                                                <img src="/img/service-img/<?php echo $service['id'];?>/<?php echo $service['image']; ?>"                                                          
                                                                     alt="Ogledi.bg"                                                           
                                                                     >
                                                                <span class="zoom" style="width: 354; height: 100%; line-height: 218px;"></span>
                                                            </a>
                                                            <div class="grid-content">
                                                                <h4><a href="<?php echo $this->url('languageRoute/servicePost', array('lang' => $_SESSION['lang'], 'url' => $service['url'])); ?>"><?php echo $service['title']; ?></a></h4>
                                                                <span class="meta-data"><span><i class="fa fa-calendar"></i><?php echo $service['date_published']; ?></span></span>
                                                                <p><?php echo mb_substr(strip_tags($service['description']), 0, 80, 'utf-8'); ?></p>
                                                            </div>
                                                        </div>
                                                    </li>
                                                <?php endif; ?>
                                            <?php endforeach; ?>                                
                                        <?php endforeach; ?>
                                    </ul>            
                                </div>       
                            </div>         
                            <div>
                                <ul class="paginationX desktop-show">
                                    <?php if ($this->page == 1) { ?>
                                        <li class="btn btn-default" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li><a class="btn btn-default" href="?page=1">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</a></li>
                                    <?php } ?>
                                    <?php for ($i = 1; $i <= $this->maxPages; $i++) { ?>
                                        <?php if ($this->page == $i) { ?>
                                            <li class="btn btn-default" style="background:#ccc;"><span>&nbsp;<?php echo $i; ?>&nbsp;</span></li>
                                        <?php } else { ?>
                                            <li><a href="?page=<?php echo $i; ?>" class="btn btn-default" >&nbsp;<?php echo $i; ?>&nbsp;</a></li>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php if ($this->page == $this->maxPages) { ?>
                                        <li class="btn btn-default" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li><a class="btn btn-default" href="?page=<?php echo $this->maxPages; ?>">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</a></li>
                                    <?php } ?>                                 
                                </ul>
                            </div> 
                            <div>
                                <ul class="paginationX mobile-show">
                                    <?php if ($this->page == 1) { ?>
                                        <li class="btn btn-default paginationX-first" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li class="paginationX-first"><a class="btn btn-default" href="?page=1">&nbsp; <?php echo $this->language()->translate('First'); ?> &nbsp;</a></li>
                                    <?php } ?>

                                    <?php if ($this->page == $this->maxPages) { ?>
                                        <li class="btn btn-default paginationX-last" style="background: #CCC;">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</li>
                                    <?php } else { ?>
                                        <li class="paginationX-last"><a class="btn btn-default" href="?page=<?php echo $this->maxPages; ?>">&nbsp; <?php echo $this->language()->translate('Last'); ?> &nbsp;</a></li>
                                    <?php } ?>

                                    <br>&nbsp;
                                    <br>&nbsp;
                                    <br>&nbsp;
                                    <?php for ($i = 1; $i <= $this->maxPages; $i++) { ?>
                                        <?php if ($this->page == $i) { ?>
                                            <li class="btn btn-default paginationX-middle" style="background:#ccc;"><span>&nbsp;<?php echo $i; ?>&nbsp;</span></li>
                                        <?php } else { ?>
                                            <li><a href="?page=<?php echo $i; ?>" class="btn btn-default paginationX-middle" >&nbsp;<?php echo $i; ?>&nbsp;</a></li>
                                            <?php } ?>
                                        <?php } ?>
                                </ul>
                            </div>
                        <?php } else { ?>
                            <?php echo $this->language()->translate('No results for this category'); ?>                         
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>