<?php

$form = $this->form;
/* @var $form \Admin\Form\AgenciesForm */
$form->prepare();
$form->setAttribute('method', 'post');

$priceIdElement = $form->get('price_id');
$userTypeIdElement = $form->get('user_type_id');
$nameElement = $form->get('names');
$nameEnElement = $form->get('names_en');
$descriptionElement = $form->get('description');
$descriptionEnElement = $form->get('description_en');
$phoneElement = $form->get('phone');
$emailElement = $form->get('email');
$passwordElement = $form->get('password');
$passwordConfirmElement = $form->get('password_confirm');
$logoElement = $form->get('logo');
$submitElement = $form->get('submit');
$directorElement = $form->get('director');
$vatNumberElement = $form->get('vat_number');
$companyAddressElement = $form->get('company_address');
?>
<h1>Въвеждане на агенция</h1>
<div class="row">
    <div class="col-md-9 col-lg-">
        <?php echo $this->form()->openTag($form) ?>
        <input type="password" style="width:0px;height:0px;margin:0px;padding: 1px;border: 0px;">     
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($nameElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $nameElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($nameElement);
                echo $this->formElement($nameElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($nameElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($nameElement); ?></div>
            <?php } ?>
        </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($nameEnElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $nameEnElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($nameEnElement);
                echo $this->formElement($nameEnElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($nameEnElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($nameEnElement); ?></div>
            <?php } ?>
        </div>
        
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($descriptionElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $descriptionElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($descriptionElement);
                echo $this->formElement($descriptionElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($descriptionElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($descriptionElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($descriptionEnElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $descriptionEnElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($descriptionEnElement);
                echo $this->formElement($descriptionEnElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($descriptionEnElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($descriptionEnElement); ?></div>
            <?php } ?>
         </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($userTypeIdElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $userTypeIdElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($userTypeIdElement);
                echo $this->formElement($userTypeIdElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($userTypeIdElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($userTypeIdElement); ?></div>
            <?php } ?>
        </div>
        
        <div class="form-group form-elements <?php echo ($this->formElementErrors($priceIdElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $priceIdElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($priceIdElement);
                echo $this->formElement($priceIdElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($priceIdElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($priceIdElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($phoneElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $phoneElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($phoneElement);
                echo $this->formElement($phoneElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($phoneElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($phoneElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($emailElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $emailElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($emailElement);
                echo $this->formElement($emailElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($emailElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($emailElement); ?></div>
            <?php } ?>
        </div>
        
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($passwordElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $passwordElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($passwordElement);
                echo $this->formElement($passwordElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($passwordElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($passwordElement); ?></div>
            <?php } ?>
        </div>
        
        
              <div class="form-group form-elements <?php echo ($this->formElementErrors($passwordConfirmElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $passwordConfirmElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($passwordConfirmElement);
                echo $this->formElement($passwordConfirmElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($passwordConfirmElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($passwordConfirmElement); ?></div>
            <?php } ?>
        </div>
        
               <div class="form-group form-elements <?php echo ($this->formElementErrors($logoElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $logoElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($logoElement);
                echo $this->formElement($logoElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($logoElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($logoElement); ?></div>
            <?php } ?>
        </div>
        
         <div class="form-group form-elements <?php echo ($this->formElementErrors($directorElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $directorElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($directorElement);
                echo $this->formElement($directorElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($directorElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($directorElement); ?></div>
            <?php } ?>
        </div>
        <div class="form-group form-elements <?php echo ($this->formElementErrors($vatNumberElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $vatNumberElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($vatNumberElement);
                echo $this->formElement($vatNumberElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($vatNumberElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($vatNumberElement); ?></div>
            <?php } ?>
        </div>
        <div class="form-group form-elements <?php echo ($this->formElementErrors($companyAddressElement) != '') ? 'has-error' : ''; ?>">
            <div class="input-group">
                <?php
                $companyAddressElement->setLabelAttributes(array('class' => 'control-label label-text'));
                echo $this->formLabel($companyAddressElement);
                echo $this->formElement($companyAddressElement->setAttributes(array('class' => 'form-control text-input')));
                ?>
            </div>
            <?php if ($this->formElementErrors($companyAddressElement)) { ?>
                <div class="alert alert-danger"><?php echo $this->formElementErrors($companyAddressElement); ?></div>
            <?php } ?>
        </div>
        

        <?php echo $this->formButton($submitElement->setAttribute('class', 'btn btn-success')) ?>
        <button id="agenciesBack" class="btn btn-success">Назад</button>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
<script type="text/javascript">    
    
    document.getElementById("agenciesBack").onclick = function (event) {
        event.preventDefault(); 
        location.href = '<?php echo $this->url('languageRoute/adminAgencies'); ?>';
    };
    
</script>